Repository lakshya076/Cinematch, pull requests merged in 2023-11, with the labels that each got.

#9 Arnav 6.0
  backend/collaborative_filtering.py
  backend/users.py
  main.py
  reusable_imports/_css.py
  reusable_imports/common_vars.py
Labels: update

#10 Fusing arnav-6 into master
  .gitignore
  main.py
  reusable_imports/_css.py
  splash_screen.py
Labels: update

#14 Fusing Arnav 6.0 into master
  .gitignore
  Icons/add_checked.ico
  Icons/add_unchecked.ico
  Icons/dark_mode.ico
  Icons/exit_main.ico
  Icons/home_checked.ico
  Icons/home_unchecked.ico
  Icons/library_checked.ico
  Icons/library_unchecked.ico
  Icons/light_mode.ico
  Icons/like_checked.ico
  Icons/like_dark.ico
  Icons/like_light.ico
  Icons/like_unchecked.ico
  Icons/logout.ico
  Icons/premium_darkmode.ico
  Icons/premium_lightmode.ico
  Icons/random_checked.ico
  Icons/random_unchecked.ico
  Icons/search_checked.ico
  Icons/search_unchecked.ico
  Icons/settings_checked.ico
  Icons/settings_unchecked.ico
  UI/ui_main.ui
  backend/collaborative_filtering.py
  backend/mapping.py
  backend/users.py
  main.py
  reusable_imports/_css.py
  reusable_imports/common_vars.py
  splash_screen.py
  startup.py
Labels: update

#16 bugfix
  backend/Utils/playlist_utils.py
  backend/users.py
Labels: bugfix

#18 merging Arnav 6.0
  .gitignore
  __pycache__/widget_generator_home.cpython-311.pyc
  backend/Utils/mapping_utils.py
  backend/Utils/movie_utils.py
  backend/Utils/playlist_utils.py
  backend/Utils/user_utils.py
  backend/collaborative_filtering.py
  backend/encryption.py
  backend/mailing.py
  backend/mapping.py
  backend/movie_search.py
  backend/playlists.py
  reusable_imports/presets.py
  reusable_imports/source_vars.py
Labels: documentation, update

#20 Arnav7
  .gitignore
  Mails/delete_account.html
  Mails/delete_permanent.html
  Mails/otp.html
  Mails/removal_warning.html
  backend/mail_former.py
  main.py
  prerequisites.py
Labels: update, bugfix
